apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cloudide-vs
spec:
  hosts:
  - "*"
  gateways:
  - cloudide-gateway
  http:
  - match:
    - uri:
        exact: /
    - uri:
        prefix: /ide
    rewrite:
      uri: /ide
    route:
    - destination:
        host: ui-app-service
        port:
          number: 80
  - match:
    - uri:
        # TODO versioning
        prefix: /api/v1
    route:
    - destination:
        host: ui-manager-service
        port:
          number: 5000
