apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- role.yaml
- sa.yaml
- rolebinding.yaml

images:
- name: ui-manager
  newName: andriisoft/cloudide-ui-manager
  newTag: latest
