apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ui-manager-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - cloudide.com
  resources:
  - users
  verbs:
  - create
