apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ui-manager-role-binding
subjects:
- kind: ServiceAccount
  name: ui-manager-sa
roleRef:
  kind: ClusterRole
  name: ui-manager-role
  apiGroup: rbac.authorization.k8s.io
