apiVersion: cloudide.com/v1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: user
    app.kubernetes.io/instance: user-sample
    app.kubernetes.io/part-of: usercontroller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: usercontroller
  name: user-sample
spec:
  name: admin
  username: test
