apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mysql-ns

resources:
- namespace.yaml
- deployment.yaml
- pvc.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: mysql-parameters
  envs:
  - params.env

#only for mac

images:
- name: mysql
  newName: arm64v8/mysql
  newTag: "8"

# vars:
# - name: MYSQL_ROOT_PASSWORD
#   objref:
#     kind: ConfigMap
#     name: mysql-parameters
#     apiVersion: v1
#   fieldref:
#     fieldpath: data.MYSQL_ROOT_PASSWORD
# configurations:
# - params.yaml
