apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      containers:
      - name: ui
        image: ui-image
        env:
        - name: REACT_APP_EXECUTOR_URI
          valueFrom:
            configMapKeyRef:
              name: ui-parameters
              key: REACT_APP_EXECUTOR_URI
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
