apiVersion: v1
kind: Service
metadata:
  name: ui-app-service
spec:
  selector:
    app: ui-app
  type: NodePort
  ports:
  - name: ui
    port: 80
    targetPort: 3000
    nodePort: 31000
    protocol: TCP
